[audio]
sample_rate = 44100
channels = 1

[output]
command = "afplay"
args = ["-v", "0.3"]

[mapping]
play = '>'
wait = ':'
wave = '~'
repeat = '|'
repeat_line = '||'
debug = '#'

[symbols]
reference = '@'
