[lane.standNbleed]
# Tue 23 Jun - parser for Lane is done, starting musical dev log
# Better to be called as
# @standNbleed:a3:e4
# @standNbleed:a4:e4
vars = 'b:a3 o3:b+7 o2:o3+4'
tick = '1/4'
content = '''
>b-12:8 | >b   <+4 >o3 >o2:5
>b-10:8 | >b+2 <+4 >o3 >o2   <+3 <-3 >b+6 >o3
>b-8:8  | >b+4 <+2 >o3 >o2:5
>b-10:8 | >b+2 <+4 >o3 >b+6  <+1 <-5 <+4  <-4
'''

[lane.testRiff1]
# Fri 26 Jun - parser for Riff is partialy done, first melody made
# Better to be called as
# A:a2+8
# >A-8:7 >A-5
# @testRiff1Bass:A-8 	  < <+4 <
# @testRiff1:A 	          < <+4 <
# @testRiff1:A+8 	      < <+4 <
# @testRiff1Lead:A+2:A+9  < <+4 <
# @testRiff1:A+2 	      < <+4 <
# @testRiff1:A+2 	      < <+4 <
# >A-10:4
vars = 'A:e3'
content = '''
@testRiff1Bass:A-12 | @testRiff1Lead:A
'''
[riff.testRiff1Bass]
tick = '1/4'
vars = 'd:e2 e:d+7'
content = '''
d d > >  e _ d _
'''
[riff.testRiff1Lead]
tick = '1/4'
vars = 'a:e3 b:a+3 c:b+4'
content = '''
a b a b  a b c b
'''

[lane.testTicks]
# Thu 2 Jul - implemented time manipulations via 'tick' property
# Refactored CLI, now I can play by sequence name
# Additionaly added some Vim keybindings to play with, its fun, really
vars = 'A:e2 B:A+7 d:32'
content = '''
@testTicksCombo:A:A+12:d
@testTicksRiff:B:d    <
@testTicksCombo:A:B:d <
@testTicksCombo:A:B:d <
'''
[lane.testTicksRiff]
vars = 'A:e2 d:24'
tick = '8/d'
content = '''
>A < < <+3:/2 <-2 _ <:*2 < <-3
'''
[lane.testTicksCombo]
vars = 'A:e2 B:A+12 d:24 d2:d/2'
content = '''
@testTicksRiff:A:d2 |
@testTicksRiff:B:d  <
'''

[lane.noSleep]
# Fri 3 Jul 2:47 - melody translated from guitar in Riff and then in Lane
# Also, found out that we can have oneline helpers in shared 'lane' or 'riff' sections
# Can be usefull
content = '@noSleepRiff @noSleepLane @chordShort:a2 | @arpegShort:a3:4'
[riff.noSleepRiff]
vars = 'T:a2 D:2'
tick = '1/D'
tune = 'T'
content = '''
7 > > <+2:.5 <+2 | 4+7 > > <+1:.5 <-1
0 > > >          | 4   > > >
'''
[lane.noSleepLane]
vars = 'T:0 D:2'
tick = '1/D'
tune = 'T'
content = '''
>a2:4  |<+7:3 |_3 <+2:.5 <+2
>cs3:4 |<+7:3 |_3 <+1:.5 <-1
'''
[lane]
chordShort={vars='note:e2 D:1',tick='1/D',content='>note |<+7'}
arpegShort={vars='note:e2 D:1',tick='1/D',content='>note <+7 <+5 <-5'}

[lane.graur]
# Thu 9 Jul 3:55 - was inspired by "graur" tracks
# Also enhanced play and added stop command to run multiple bleeder instances
content = '''
@nobodyClaimingMe <
@iDontBelongHere <
'''
[riff]
rep={vars='T:e1',tune='T',content='0 12 0 12'}

[lane.iDontBelongHere]
vars = 'T:e1 D:4'
tick = '1/D'
tune = 'T'
content = '''
@rep:9 <5 <0 <4
'''
[lane.nobodyClaimingMe]
vars = 'T:e1 D:4'
tick = '1/D'
tune = 'T'
content = '''
@rep:0 <
@rep:8 >8 <+12 >8 _
@rep:7 <
@rep:7 <1
'''
