[meta]
include = [
'dev_log_bleeds.toml'
]

[lane.main]
tune = 'd1'
tick = '0.88'
content = '''
@ppunkRiff:5:0
@ppunkRiff:1:0

@ppunkRiff:5:2
@ppunkRiff:1:7

>5+24:3:.4 | @ppunkRiff:5:0
>6+24:3:.4 | @ppunkRiff:1:0

>10+24:3:.4 | @ppunkRiff:5:2
>12+24:2:.4 | @ppunkRiff:1:7
'''

[lane.mySong]
vars = 'a:40 b:a-2'
content = '@myRiff:b'

[riff.myRiff]
vars = 'n:40'
content = 'n'

[riff.masterRiff1]
vars = 'T:e1 D:4 V:1'
tick = '1/D'
tune = 'T'
gain = 'V'
content = '''
0 1 7 0 1 8 0 1 9 0 1 8 0 1 7 7 |
0 1 7 0 1 8 0 1 9 0 1 8 0 1 7 >
'''

[riff.ppunkRiff]
vars = 'T:e1 add:0 D:6 V:1 n:5+add'
tick = '1/D'
tune = 'T'
gain = 'V'
content = '''
5 > 5 5  5 5 5 5 |
5 5 5 5  n n n 0
'''

[lane.ppunkBg]
vars = 'T:e1 add:0 D:6 V:1 n:5+add'
tick = '1/D'
tune = 'T+12'
gain = 'V'
content = '''
>5:16:.6
'''
