[meta]
include = [
'dev_log_bleeds.toml'
]

[lane.main]
tick = '1'
tune = 'b1'
# tick = '1/4'
content = '''
@ppunkRiff:8:7
@ppunkRiff:4:7
'''

[riff.minorScale]
tune = 'g1'
tick = '1/4'
content = '''
0  2  3  5  7  8  10
12 14 15 17 19 20 22
'''

[riff.test]
vars = 'tone:0 off:tone%2'
tune = 'g1+tone'
tick = '1/4'
content = '''
0+off 7 8+off
'''

[riff.mainRiff]
tick = '1/6'
vars = 'a:0 b:0'
content = '''
0 7 0 14+a 12+b
'''

[lane.mySong]
vars = 'a:40 b:a-2'
content = '@myRiff:b'

[riff.myRiff]
vars = 'n:40'
content = 'n'

[riff.masterRiff1]
vars = 'T:e1 D:4 V:1'
tick = '1/D'
tune = 'T'
gain = 'V'
content = '''
0 1 7 0 1 8 0 1 9 0 1 8 0 1 7 7 |
0 1 7 0 1 8 0 1 9 0 1 8 0 1 7 >
'''

[riff.ppunkRiff]
vars = 'T:e1 add:0 D:5 V:1 n:5+add'
tick = '1/D'
tune = 'T'
gain = 'V'
content = '''
5 > 5 5  5 5 5 5 |
5 5 5 5  n n n 0
'''

[riff.ppunkBg]
vars = 'T:e1 add:0 D:5 V:1 n:5+add'
tick = '1/D'
tune = 'T+12'
gain = 'V'
content = '''
5 > 9 _ 5 > 9 _ |
12 12 10 10 9 9 5 5
'''
